"""empty message

Revision ID: 44aca7a64a80
Revises: None
Create Date: 2014-10-02 22:08:32.882752

"""

# revision identifiers, used by Alembic.
revision = '44aca7a64a80'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###
